Added Post about DevOps Definition
wyll-io/blog pull request #2
Opened 2022-08-31 06:09 UTC by Unshortafleur

Committer: VENTURA LUCAS <ventura.lgh@gmail.com>

 On branch Post_Lucas_V
 Changes to be committed:
	new file:   What-is-DevOps.md

2022-08-31 07:33 UTC, fallais commented
Salut @Unshortafleur , peux-tu nommer le fichier en minuscule stp ?

2022-08-31 08:06 UTC, fallais requested changes

2022-08-31 08:06 UTC, fallais commented on content/posts/What-is-DevOps.md
> +![What is the difference between continuous delivery and continuous deployment?  - Quora](https://qph.cf2.quoracdn.net/main-qimg-a82fe747cc53bd5dadb0ccee0f02af5c-pjlq)
Ne mets pas de lien vers des ressources externes, mets l'image dans le dossier `blog/static/images/posts/`, et pointes vers ça

2022-08-31 08:06 UTC, fallais commented on content/posts/What-is-DevOps.md
> +
Avant de commencer l'article, ça serait bien de mettre une phrase qui résume ce que tu vas expliquer, pourquoi tu fais cet article, etc... ;)

2022-08-31 08:06 UTC, fallais commented on content/posts/What-is-DevOps.md
> +# What is DevOps ?
Avant le titre principal, il manque les entêtes du post, regarde mes autres post pour copier/coller et adapter.

2022-08-31 09:51 UTC, Unshortafleur commented on content/posts/What-is-DevOps.md
> +DevOps is an approach that brings together the two main functions of a company's Information Systems Department. It brings together the development team (Dev) and the system operations team (Ops).
Ca me va, effectivement c'est plus parlant comme ça.

2022-09-12 09:06 UTC, fallais commented
@Unshortafleur : tu peux ajouter des ** sur les mots importants pour les mettre en gras stp ? Ca améliorera la lisibilité, par exemple dans le chapitre "continuous deployment", sans abuser bien sûr :P

2022-09-13 11:02 UTC, Unshortafleur commented
@fallais J'ai mis les mots techniques et importants en gras, mem quand ils sont répétés au cours de l'article. J'ai pas voulu forcer mais je trouve ça plus logique. T'en penses quoi ?

2022-09-28 16:03 UTC, fallais approved these changes

2022-09-28 16:03 UTC, merged